# --- この内容で Dockerfile-tomcat を完全に上書きしてください ---

# Tomcatの公式イメージをベースとする (Java 17対応版)
FROM tomcat:9.0-jdk17-openjdk

# ローカルにある「AMS.war」ファイルを、コンテナ内の「/usr/local/tomcat/webapps/」にコピーします。
# これにより、Tomcatが自動的にアプリケーションをデプロイします。
COPY AMS.war /usr/local/tomcat/webapps/

# --- 上書きはここまで ---
