# --- この内容で docker-compose.yml を完全に上書きしてください ---

version: '3.8'

services:
  # ------------------------------------
  # 1. あなたのWebアプリケーション (Tomcat)
  # ------------------------------------
  ams:
    # ローカルのDockerfileからビルドします
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    container_name: AMS
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - my-app-network

  # ------------------------------------
  # 2. MySQL データベース - 【修正箇所】
  # ------------------------------------
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      # rootユーザーのパスワードを空にする設定
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # ★★★ 作成するデータベースの名前を「AMS」に変更 ★★★
      MYSQL_DATABASE: AMS
    volumes:
      - mysql-data:/var/lib/mysql
      # このフォルダ内のSQLが初回起動時に実行されます
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - my-app-network
    restart: always

  # ------------------------------------
  # 3. phpMyAdmin (データベース管理ツール)
  # ------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-app
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
    depends_on:
      - mysql-db
    networks:
      - my-app-network
    restart: always

# ------------------------------------
# ネットワークとボリュームの定義
# ------------------------------------
networks:
  my-app-network:
    driver: bridge

volumes:
  mysql-data:

# --- 上書きはここまで ---
